//--------------------------------------------------
// REGISTERS
//--------------------------------------------------
.const RP = $52		// Register pointer

.const r0 = RP		// 16-bit registers
.const r1 = RP + 2
.const r2 = RP + 4
.const r3 = RP + 6
.const r4 = RP + 8
.const r5 = RP + 10
.const r6 = RP + 12
.const r7 = RP + 14
.const r8 = RP + 16
.const r9 = RP + 18
.const r10 = RP + 20
.const r11 = RP + 22
.const r12 = RP + 24
.const r13 = RP + 26
.const r14 = RP + 28
.const r15 = RP + 30
.const r16 = RP + 32
.const r17 = RP + 34
.const r18 = RP + 36
.const r19 = RP + 38
.const r20 = RP + 40

.const rr0 = RP		// 32-bit registers
.const rr2 = RP + 4
.const rr4 = RP + 8
.const rr6 = RP + 12
.const rr8 = RP + 16
.const rr10 = RP + 20
.const rr12 = RP + 24
.const rr14 = RP + 28
.const rr16 = RP + 32
.const rr18 = RP + 36
